/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#fdfcfc',
        ink: '#201d1d',
        'ink-deep': '#0f0000',
        charcoal: '#302c2c',
        body: '#424245',
        mute: '#646262',
        stone: '#6e6e73',
        ash: '#9a9898',
        'surface-soft': '#f8f7f7',
        'surface-card': '#f1eeee',
        'surface-dark': '#201d1d',
        'surface-dark-elevated': '#302c2c',
        hairline: 'rgba(15,0,0,0.12)',
        'hairline-strong': '#646262',
        accent: '#007aff',
        'accent-hover': '#0056b3',
        'accent-active': '#004085',
        danger: '#ff3b30',
        'danger-hover': '#d70015',
        'danger-active': '#a50011',
        warning: '#ff9f0a',
        'warning-hover': '#cc7f08',
        'warning-active': '#995f06',
        success: '#30d158',
      },
      fontFamily: {
        sans: ['JetBrains Mono', 'IBM Plex Mono', 'ui-monospace', 'monospace'],
        mono: ['JetBrains Mono', 'IBM Plex Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-xl': ['38px', { lineHeight: '1.5', fontWeight: '700' }],
        'heading-md': ['16px', { lineHeight: '1.5', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'button-md': ['16px', { lineHeight: '2.0', fontWeight: '500' }],
        'caption-md': ['14px', { lineHeight: '2.0', fontWeight: '400' }],
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        DEFAULT: '4px',
        md: '4px',
        lg: '4px',
        xl: '0px',
        '2xl': '0px',
      },
      boxShadow: {
        none: 'none',
      },
    },
  },
  plugins: [],
}
